Desktop version
maaloum/PortFolio pull request #4
Opened 2022-07-06 11:55 UTC by maaloum

In this project, I add :
- navbar to index.html
- Media queries to control different sizes.
- Linters
- Update style.css

2022-07-06 13:13 UTC, omarsalem7 requested changes
Hi @maaloum 😊, 

Good job so far! 👏
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

![you-are-near](https://media.giphy.com/media/SSR17K6yZWvGCYrfUh/giphy.gif)

## Highlights
- Descriptive pull request ✔️
- No linter errors ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-06 13:13 UTC, omarsalem7 commented on style.css
> +    align-items: center;
- [ ] consider matching your design like the one in the Figma template by specifying the correct padding and margins for work cards section 

- [ ] Also consider adding the correct background color for the work section like the Figma design.
- [ ] Kindly add appropriate padding and margin for about section

| Your design  | Figma design|
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/53402600/177556111-c46be900-ad43-4ccd-839b-b9b2dd73108f.png)| ![image](https://user-images.githubusercontent.com/53402600/177556259-7e3aaf21-03d6-4e3b-9d76-25aabcd37b8d.png) |
| ![image](https://user-images.githubusercontent.com/53402600/177557163-67b37592-c3cf-476d-8457-03272e198e3d.png) | ![image](https://user-images.githubusercontent.com/53402600/177557238-afb74457-25f1-4087-bd77-fc52f3d432a8.png)
 |

2022-07-07 11:02 UTC, mugishasam123 requested changes
Hi  @maaloum  ✋ , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![ALT](https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

 ## Highlights
- Linters are passing ✔️ 
- NIce use of Github flow 🥇 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-07 11:47 UTC, Reem-lab approved these changes
## Hi @maaloum, 👋🏻👋🏻 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉🔥🔥 
<img src="https://media2.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif"/>

## Highlights✨
- No linters error ✅✅
- Great job on working on the requested changes ✅🔥🔥
- Good commit messages 🔥🔥

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-07 11:49 UTC, merged